---
- name: Mein erster Ansible-Test
  hosts: local
  gather_facts: true

  tasks:
    - name: Betriebssystem anzeigen
      ansible.builtin.debug:
        msg: "System: {{ ansible_facts['system'] }}"

    - name: Rechnername anzeigen
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_facts['hostname'] }}"

    - name: Testdatei erstellen
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/ansible-test.txt"
        state: touch
        mode: "0644"

